import type {
  User, Task, ContentItem, Campaign, Asset, Metric, Notification, WeeklyFocus, InternalEvent,
} from "./types";

export const USERS: User[] = [
  {
    id: "hugo",
    name: "Hugo",
    email: "hugo@blindsaint.co",
    role: "admin",
    initials: "HG",
    color: "#c8102e",
    area: "Líder / Dirección creativa de drops / Diseño de prendas",
    status: "online",
  },
  {
    id: "luca",
    name: "Luca",
    email: "luca@blindsaint.co",
    role: "operations",
    initials: "LC",
    color: "#f0f0ee",
    area: "CTO + CFO",
    status: "online",
  },
  {
    id: "carlos",
    name: "Carlos",
    email: "carlos@blindsaint.co",
    role: "marketing",
    initials: "CR",
    color: "#2a2a2a",
    area: "Director RRSS / Marketing / Métricas",
    status: "online",
  },
  {
    id: "mauro",
    name: "Mauro",
    email: "mauro@blindsaint.co",
    role: "content",
    initials: "MR",
    color: "#8c8c8c",
    area: "Community Manager / Contenido",
    status: "busy",
  },
];

export const TASKS: Task[] = [
  {
    id: "t1",
    title: "Diseñar mockups Drop 002",
    description: "Crear mockups en 3 colorways para la colección capsule Drop 002. Formato: fotoproducto plano + mannequin.",
    assigneeId: "luca",
    priority: "critical",
    status: "in_progress",
    dueDate: "2025-06-12",
    type: "design",
    tags: ["drop002", "mockup"],
    comments: [
      { id: "c1", userId: "hugo", text: "Necesitamos el negro principal listo para el teaser del martes.", createdAt: "2025-06-08T10:30:00Z" },
    ],
    checklist: [
      { id: "cl1", text: "Colorway negro / blanco", done: true },
      { id: "cl2", text: "Colorway washed grey", done: false },
      { id: "cl3", text: "Colorway bone", done: false },
    ],
    campaignId: "camp2",
    createdAt: "2025-06-01T09:00:00Z",
    updatedAt: "2025-06-08T10:30:00Z",
  },
  {
    id: "t2",
    title: "Configurar página Drop 002 en Shopify",
    description: "Crear colección, productos, variantes, precios y metafields. Usar el theme actual.",
    assigneeId: "carlos",
    priority: "high",
    status: "todo",
    dueDate: "2025-06-14",
    type: "shopify",
    tags: ["drop002", "shopify", "ecom"],
    comments: [],
    checklist: [
      { id: "cl4", text: "Crear colección Drop 002", done: false },
      { id: "cl5", text: "Añadir variantes de tallas", done: false },
      { id: "cl6", text: "Configurar stock inicial", done: false },
      { id: "cl7", text: "Test compra de prueba", done: false },
    ],
    campaignId: "camp2",
    createdAt: "2025-06-02T11:00:00Z",
    updatedAt: "2025-06-05T14:00:00Z",
  },
  {
    id: "t3",
    title: "Grabar teaser reel Drop 002",
    description: "Vídeo 15-30s con estética oscura, warehouse. Sin cara. Solo prenda + hands + ambiente.",
    assigneeId: "mauro",
    priority: "high",
    status: "in_progress",
    dueDate: "2025-06-11",
    type: "video",
    tags: ["drop002", "reel", "teaser"],
    comments: [
      { id: "c2", userId: "hugo", text: "Referencia: @corteiz warehouse drop footage. Ultra dark, high contrast.", createdAt: "2025-06-07T16:00:00Z" },
    ],
    checklist: [
      { id: "cl8", text: "Storyboard aprobado", done: true },
      { id: "cl9", text: "Sesión de grabación", done: false },
      { id: "cl10", text: "Edición + color grading", done: false },
      { id: "cl11", text: "Aprobación final", done: false },
    ],
    campaignId: "camp2",
    createdAt: "2025-06-03T10:00:00Z",
    updatedAt: "2025-06-08T09:00:00Z",
  },
  {
    id: "t4",
    title: "Escribir copies Drop 002 — todos los canales",
    description: "Copies para stories, feed, TikTok, email y WhatsApp. Tono: críptico, urgente, escasez.",
    assigneeId: "hugo",
    priority: "high",
    status: "todo",
    dueDate: "2025-06-13",
    type: "content",
    tags: ["drop002", "copy", "all-channels"],
    comments: [],
    checklist: [
      { id: "cl12", text: "Copy TikTok (3 vídeos)", done: false },
      { id: "cl13", text: "Copy stories countdown", done: false },
      { id: "cl14", text: "Copy email announcement", done: false },
      { id: "cl15", text: "Copy WhatsApp blast", done: false },
    ],
    campaignId: "camp2",
    createdAt: "2025-06-04T08:00:00Z",
    updatedAt: "2025-06-04T08:00:00Z",
  },
  {
    id: "t5",
    title: "Configurar Meta Ads Drop 002",
    description: "Crear campañas de retargeting y awareness en Meta Ads. Budget: €200. Objetivo: tráfico Shopify.",
    assigneeId: "carlos",
    priority: "medium",
    status: "backlog",
    dueDate: "2025-06-15",
    type: "paid_ads",
    tags: ["drop002", "meta", "ads"],
    comments: [],
    checklist: [],
    campaignId: "camp2",
    createdAt: "2025-06-05T12:00:00Z",
    updatedAt: "2025-06-05T12:00:00Z",
  },
  {
    id: "t6",
    title: "Fotografía editorial Drop 001 — segunda sesión",
    description: "Retoque y selección de 15 fotos finales de la segunda sesión editorial.",
    assigneeId: "luca",
    priority: "medium",
    status: "review",
    dueDate: "2025-06-10",
    type: "photo",
    tags: ["drop001", "editorial"],
    comments: [
      { id: "c3", userId: "mauro", text: "Las fotos en la sesión 2 con el muro de ladrillo están muy buenas.", createdAt: "2025-06-06T15:00:00Z" },
    ],
    checklist: [
      { id: "cl16", text: "Selección de 30 mejores", done: true },
      { id: "cl17", text: "Retoque color", done: true },
      { id: "cl18", text: "Selección final 15", done: false },
      { id: "cl19", text: "Export para web y social", done: false },
    ],
    campaignId: "camp1",
    createdAt: "2025-05-20T10:00:00Z",
    updatedAt: "2025-06-07T11:00:00Z",
  },
  {
    id: "t7",
    title: "Actualizar About en la web",
    description: "Reescribir la sección About con el nuevo manifiesto. Añadir fotos del equipo.",
    assigneeId: "hugo",
    priority: "low",
    status: "backlog",
    dueDate: "2025-06-25",
    type: "web",
    tags: ["web", "brand"],
    comments: [],
    checklist: [],
    createdAt: "2025-06-01T09:00:00Z",
    updatedAt: "2025-06-01T09:00:00Z",
  },
  {
    id: "t8",
    title: "URGENTE: resolver fallo pasarela Stripe",
    description: "Los pagos con Visa están fallando en producción. Revisar webhook y logs de Stripe.",
    assigneeId: "carlos",
    priority: "critical",
    status: "blocked",
    dueDate: "2025-06-09",
    type: "shopify",
    tags: ["bug", "stripe", "crítico"],
    comments: [
      { id: "c4", userId: "carlos", text: "Soporte de Stripe ha abierto ticket. Esperando respuesta.", createdAt: "2025-06-08T08:00:00Z" },
    ],
    checklist: [
      { id: "cl20", text: "Identificar el error en los logs", done: true },
      { id: "cl21", text: "Contactar soporte Stripe", done: true },
      { id: "cl22", text: "Aplicar fix en producción", done: false },
      { id: "cl23", text: "Verificar que los pagos vuelven a funcionar", done: false },
    ],
    createdAt: "2025-06-08T07:00:00Z",
    updatedAt: "2025-06-08T09:30:00Z",
  },
  {
    id: "t9",
    title: "Crear playlist editorial BlindSaint para shoots",
    description: "Playlist en Spotify de 2h con el mood exacto de la marca para usar en futuras sesiones.",
    assigneeId: "mauro",
    priority: "low",
    status: "done",
    dueDate: "2025-06-05",
    type: "other",
    tags: ["creative", "mood"],
    comments: [],
    checklist: [
      { id: "cl24", text: "Selección de tracks UK Drill / Dark Ambient", done: true },
      { id: "cl25", text: "Publicar y compartir con el equipo", done: true },
    ],
    createdAt: "2025-05-28T10:00:00Z",
    updatedAt: "2025-06-05T12:00:00Z",
  },
  {
    id: "t10",
    title: "Briefing influencers micro-tier Drop 002",
    description: "Identificar 5 perfiles UK/ES con 5k-50k seguidores. Enviar brief y muestras.",
    assigneeId: "hugo",
    priority: "medium",
    status: "in_progress",
    dueDate: "2025-06-12",
    type: "influencers",
    tags: ["drop002", "influencers"],
    comments: [],
    checklist: [
      { id: "cl26", text: "Lista de 15 candidatos", done: true },
      { id: "cl27", text: "Selección final 5 perfiles", done: true },
      { id: "cl28", text: "Enviar brief oficial", done: false },
      { id: "cl29", text: "Confirmar participación", done: false },
    ],
    campaignId: "camp2",
    createdAt: "2025-06-06T09:00:00Z",
    updatedAt: "2025-06-08T11:00:00Z",
  },
];

export const CONTENT_ITEMS: ContentItem[] = [
  {
    id: "con1",
    title: "Teaser Drop 002 — sombras y textura",
    platform: "instagram_reels",
    format: "teaser",
    publishDate: "2025-06-11",
    publishTime: "19:00",
    assigneeId: "mauro",
    status: "in_production",
    copy: "Coming. No warnings. 06.16 — @blindsaint_co",
    campaignId: "camp2",
    objective: "Build hype + alcance orgánico",
    cta: "Follow for the drop",
    expectedMetric: 15000,
    tags: ["drop002", "teaser"],
  },
  {
    id: "con2",
    title: "Countdown stories Day 5",
    platform: "instagram_stories",
    format: "scarcity",
    publishDate: "2025-06-12",
    publishTime: "18:00",
    assigneeId: "mauro",
    status: "scheduled",
    copy: "5 days. Limited stock. No restock.",
    campaignId: "camp2",
    tags: ["drop002", "countdown"],
  },
  {
    id: "con3",
    title: "Countdown stories Day 4",
    platform: "instagram_stories",
    format: "scarcity",
    publishDate: "2025-06-13",
    publishTime: "18:00",
    assigneeId: "mauro",
    status: "scheduled",
    copy: "4 days. You've been warned.",
    campaignId: "camp2",
    tags: ["drop002", "countdown"],
  },
  {
    id: "con4",
    title: "BTS grabación Drop 002 — warehouse",
    platform: "tiktok",
    format: "bts",
    publishDate: "2025-06-12",
    publishTime: "20:00",
    assigneeId: "mauro",
    status: "ready",
    copy: "Not a fashion brand. A system. #blindsaint #streetwear #ukdrill",
    campaignId: "camp2",
    objective: "Autenticidad + awareness TikTok",
    cta: "Link in bio",
    expectedMetric: 25000,
    tags: ["drop002", "bts", "tiktok"],
  },
  {
    id: "con5",
    title: "Drop announcement email",
    platform: "email",
    format: "drop_announcement",
    publishDate: "2025-06-16",
    publishTime: "09:00",
    assigneeId: "hugo",
    status: "scheduled",
    copy: "DROP 002 — BLIND BOX SYSTEM — AVAILABLE NOW",
    campaignId: "camp2",
    objective: "Conversión directa a Shopify",
    cta: "ENTER THE DROP",
    expectedMetric: 500,
    tags: ["drop002", "email"],
  },
  {
    id: "con6",
    title: "Post Drop 001 — recap editorial",
    platform: "instagram_feed",
    format: "editorial",
    publishDate: "2025-06-09",
    publishTime: "19:00",
    assigneeId: "luca",
    status: "ready",
    copy: "DROP 001 — SOLD. The first chapter is closed.",
    campaignId: "camp1",
    realMetric: 4200,
    tags: ["drop001", "recap"],
  },
  {
    id: "con7",
    title: "Reel editorial Drop 002 — producto final",
    platform: "instagram_reels",
    format: "reel",
    publishDate: "2025-06-16",
    publishTime: "19:00",
    assigneeId: "mauro",
    status: "in_production",
    campaignId: "camp2",
    objective: "Presentación producto en el día del drop",
    expectedMetric: 30000,
    tags: ["drop002", "launch"],
  },
  {
    id: "con8",
    title: "WhatsApp blast — drop live",
    platform: "whatsapp",
    format: "launch_reminder",
    publishDate: "2025-06-16",
    publishTime: "10:00",
    assigneeId: "carlos",
    status: "scheduled",
    copy: "🔒 DROP 002 LIVE NOW — LIMITED. blindsaint.co/drop002",
    campaignId: "camp2",
    tags: ["drop002", "whatsapp"],
  },
  {
    id: "con9",
    title: "Meme scarcity — drops cultura",
    platform: "tiktok",
    format: "meme",
    publishDate: "2025-06-14",
    publishTime: "21:00",
    assigneeId: "mauro",
    status: "idea",
    tags: ["organic", "humor"],
  },
  {
    id: "con10",
    title: "UGC repost — cliente Drop 001",
    platform: "instagram_stories",
    format: "ugc",
    publishDate: "2025-06-10",
    publishTime: "17:00",
    assigneeId: "hugo",
    status: "ready",
    campaignId: "camp1",
    tags: ["drop001", "ugc", "community"],
  },
];

export const CAMPAIGNS: Campaign[] = [
  {
    id: "camp1",
    name: "Drop 001 — VOID",
    description: "Primera colección de BlindSaint. Blind box system. 50 unidades.",
    startDate: "2025-04-01",
    launchDate: "2025-05-01",
    closeDate: "2025-05-15",
    status: "closed",
    objective: "Lanzar la marca, generar primeros clientes, crear expectativa.",
    product: "Blind Box S/S 2025 — VOID",
    price: 85,
    stock: 50,
    targetSales: 50,
    realSales: 47,
    leadId: "hugo",
    teamIds: ["hugo", "luca", "mauro", "carlos"],
    checklist: {
      productDefined: true, mockupsReady: true, photosReady: true,
      pageReady: true, stockValidated: true, priceValidated: true,
      copiesReady: true, calendarClosed: true, emailReady: true,
      storiesReady: true, reelsReady: true, influencersActivated: true,
      paymentTested: true, testPurchaseDone: true, finalPublicationValidated: true,
    },
    contentIds: ["con6", "con10"],
    taskIds: ["t6", "t9"],
    notes: "Drop exitoso. 47/50 vendidas en las primeras 6h. Bugfix en Stripe el día del drop.",
    coverColor: "#2a2a2a",
  },
  {
    id: "camp2",
    name: "Drop 002 — SIGNAL",
    description: "Segunda colección. Capsule con 3 prendas. Blind box + individual. 80 unidades totales.",
    startDate: "2025-06-01",
    launchDate: "2025-06-16",
    closeDate: "2025-06-30",
    status: "teasing",
    objective: "Doblar ventas respecto al Drop 001. Activar influencers micro. Consolidar comunidad.",
    product: "Capsule S/S 2025 — SIGNAL",
    price: 95,
    stock: 80,
    targetSales: 75,
    realSales: 0,
    leadId: "hugo",
    teamIds: ["hugo", "luca", "mauro", "carlos"],
    checklist: {
      productDefined: true, mockupsReady: false, photosReady: false,
      pageReady: false, stockValidated: true, priceValidated: true,
      copiesReady: false, calendarClosed: true, emailReady: false,
      storiesReady: false, reelsReady: false, influencersActivated: false,
      paymentTested: false, testPurchaseDone: false, finalPublicationValidated: false,
    },
    contentIds: ["con1", "con2", "con3", "con4", "con5", "con7", "con8"],
    taskIds: ["t1", "t2", "t3", "t4", "t5", "t10"],
    notes: "Lanzamiento el 16 de junio. Fases: teasing 11-15 junio, live 16 junio.",
    coverColor: "#c8102e",
  },
];

export const ASSETS: Asset[] = [
  { id: "a1", name: "Logo BlindSaint — horizontal blanco", type: "logo", category: "Brand", date: "2025-03-01", authorId: "luca", tags: ["logo", "brand"], status: "approved" },
  { id: "a2", name: "Logo BlindSaint — símbolo negro", type: "logo", category: "Brand", date: "2025-03-01", authorId: "luca", tags: ["logo", "brand"], status: "approved" },
  { id: "a3", name: "Mockup tee Drop 001 — VOID negro", type: "mockup", category: "Drop 001", date: "2025-04-10", authorId: "luca", campaignId: "camp1", tags: ["drop001", "mockup"], status: "approved" },
  { id: "a4", name: "Foto editorial Drop 001 — set 1", type: "product_photo", category: "Drop 001", date: "2025-04-15", authorId: "luca", campaignId: "camp1", tags: ["drop001", "editorial"], status: "approved" },
  { id: "a5", name: "Reel teaser Drop 001 — final", type: "video", category: "Drop 001", date: "2025-04-28", authorId: "mauro", campaignId: "camp1", tags: ["drop001", "video"], status: "approved" },
  { id: "a6", name: "Brand Book v1.0", type: "brand_book", category: "Brand", date: "2025-03-15", authorId: "hugo", tags: ["brand", "guidelines"], status: "approved" },
  { id: "a7", name: "Paleta colores oficial", type: "palette", category: "Brand", date: "2025-03-01", authorId: "luca", tags: ["brand", "colors"], status: "approved" },
  { id: "a8", name: "Template story countdown", type: "story_asset", category: "Templates", date: "2025-05-01", authorId: "luca", tags: ["template", "story"], status: "approved" },
  { id: "a9", name: "Mockup tee Drop 002 — SIGNAL negro (WIP)", type: "mockup", category: "Drop 002", date: "2025-06-05", authorId: "luca", campaignId: "camp2", tags: ["drop002", "mockup"], status: "draft" },
  { id: "a10", name: "Brief influencers Drop 002", type: "document", category: "Drop 002", date: "2025-06-06", authorId: "hugo", campaignId: "camp2", tags: ["drop002", "influencers"], status: "approved" },
];

export const METRICS: Metric[] = [
  { id: "m1", name: "Followers IG", value: 4820, change: 12.4, unit: "seguidores", period: "this week" },
  { id: "m2", name: "Followers TikTok", value: 2340, change: 28.7, unit: "seguidores", period: "this week" },
  { id: "m3", name: "Alcance semanal", value: 48000, change: 34.2, unit: "personas", period: "this week" },
  { id: "m4", name: "Engagement rate", value: 6.8, change: 1.2, unit: "%", period: "this week" },
  { id: "m5", name: "Ventas Drop 001", value: 3995, change: 0, unit: "€", period: "total" },
  { id: "m6", name: "Ticket medio", value: 85, change: 0, unit: "€", period: "total" },
  { id: "m7", name: "Pedidos total", value: 47, change: 0, unit: "pedidos", period: "total" },
  { id: "m8", name: "Stock restante Drop 001", value: 3, change: 0, unit: "unidades", period: "current" },
];

export const NOTIFICATIONS: Notification[] = [
  { id: "n1", userId: "carlos", type: "task", title: "BLOQUEADO: Fallo Stripe", message: "La tarea de Stripe está bloqueada. Acción urgente requerida.", read: false, createdAt: "2025-06-08T08:00:00Z", link: "/tasks" },
  { id: "n2", userId: "hugo", type: "campaign", title: "Drop 002 — 8 días", message: "Faltan 8 días para el lanzamiento del Drop 002.", read: false, createdAt: "2025-06-08T09:00:00Z", link: "/campaigns" },
  { id: "n3", userId: "mauro", type: "content", title: "Teaser reel vence mañana", message: "El teaser reel para Instagram debe estar listo mañana.", read: true, createdAt: "2025-06-07T18:00:00Z", link: "/calendar" },
];

export const WEEKLY_FOCUS: WeeklyFocus = {
  objective: "Completar el 80% de preparación del Drop 002 antes del viernes",
  priorities: [
    "Mockups Drop 002 listos para el teaser del martes",
    "Resolver fallo de Stripe urgente",
    "Grabar y editar teaser reel Drop 002",
    "Briefing y confirmación influencers",
  ],
  risks: [
    "Stripe sigue sin funcionar — bloquea el drop",
    "Mockups no listos a tiempo para el calendario de contenido",
    "Posibles retrasos en la entrega del stock",
  ],
  activeCampaigns: ["camp2"],
  criticalContent: ["con1", "con4"],
};

export const SOCIAL_WEEKLY_DATA = [
  { day: "Lun", followers: 4680, reach: 8200, engagement: 5.2 },
  { day: "Mar", followers: 4700, reach: 9100, engagement: 6.1 },
  { day: "Mié", followers: 4720, reach: 12400, engagement: 7.8 },
  { day: "Jue", followers: 4750, reach: 15300, engagement: 8.2 },
  { day: "Vie", followers: 4780, reach: 18700, engagement: 9.1 },
  { day: "Sáb", followers: 4800, reach: 22000, engagement: 7.4 },
  { day: "Dom", followers: 4820, reach: 19500, engagement: 6.8 },
];

export const BRAND_HEALTH = {
  momentum: 74,
  execution: 62,
  contentConsistency: 58,
  dropReadiness: 45,
  communityGrowth: 81,
  salesTraction: 70,
};

export const INTERNAL_EVENTS: InternalEvent[] = [
  {
    id: "ev1",
    title: "Weekly sync — equipo completo",
    type: "meeting",
    date: "2026-06-08",
    startTime: "10:00",
    endTime: "11:00",
    attendeeIds: ["hugo", "luca", "mauro", "carlos"],
    location: "online",
    description: "Revisión semanal: prioridades, bloqueos, próximos pasos.",
  },
  {
    id: "ev2",
    title: "Review mockups Drop 002",
    type: "review",
    date: "2026-06-09",
    startTime: "16:00",
    endTime: "17:00",
    attendeeIds: ["hugo", "luca"],
    location: "office",
    description: "Validar colorways y elegir el principal para el teaser.",
  },
  {
    id: "ev3",
    title: "Sesión de grabación reel",
    type: "shoot",
    date: "2026-06-10",
    startTime: "11:00",
    endTime: "16:00",
    attendeeIds: ["mauro", "luca"],
    location: "warehouse",
    description: "Grabación teaser Drop 002. Estética dark warehouse.",
  },
  {
    id: "ev4",
    title: "1:1 Hugo + Carlos — operaciones",
    type: "1to1",
    date: "2026-06-11",
    startTime: "09:30",
    endTime: "10:00",
    attendeeIds: ["hugo", "carlos"],
    location: "online",
    description: "Estado Shopify, stock y pasarela de pagos.",
  },
  {
    id: "ev5",
    title: "Planning Drop 003",
    type: "planning",
    date: "2026-06-12",
    startTime: "15:00",
    endTime: "17:00",
    attendeeIds: ["hugo", "luca", "mauro", "carlos"],
    location: "office",
    description: "Primer brainstorm del siguiente capítulo.",
  },
  {
    id: "ev6",
    title: "Deadline copies redes",
    type: "deadline",
    date: "2026-06-13",
    attendeeIds: ["hugo"],
    description: "Todos los copies de IG/TikTok cerrados y aprobados.",
  },
  {
    id: "ev7",
    title: "Offsite estrategia Q3",
    type: "offsite",
    date: "2026-06-20",
    startTime: "10:00",
    endTime: "18:00",
    attendeeIds: ["hugo", "luca", "mauro", "carlos"],
    location: "external",
    description: "Día completo fuera para planificar Q3.",
  },
];

export const LOGIN_USERS = [
  { email: "hugo@blindsaint.co", password: "hugo2025", userId: "hugo" },
  { email: "luca@blindsaint.co", password: "luca2025", userId: "luca" },
  { email: "mauro@blindsaint.co", password: "mauro2025", userId: "mauro" },
  { email: "carlos@blindsaint.co", password: "carlos2025", userId: "carlos" },
];
